project 'MeetPets.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MeetPets' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeetPets
pod 'Alamofire'
pod 'GoogleMaps'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'ReachabilitySwift'
end
